Description:
    Marcelo Cardozo | Deployment of public S3 bucket

Parameters:
    EnvironmentName:
        Description: Environment prefixed to each resource
        Type: String
    IpAllowed:
        Description: Ip to have public access to S3 Bucket
        Type: String
        Default: 1.1.1.1/32

Resources:
    S3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: marcelor-bucket
            AccessControl: PublicRead
    BucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            PolicyDocument:
                Id: MyPolicy
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal: '*'
                      Action: 's3:GetObject'
                      Resource: !Join
                          - ''
                          - - 'arn:aws:s3:::'
                            - !Ref S3Bucket
                            - /*
                      Condition:
                          IpAddress:
                              'aws:SourceIp':
                                  - !Ref IpAllowed

            Bucket: !Ref S3Bucket