Description:
    Marcelo Cardozo | Deployment of S3 bucket

Parameters:
    EnvironmentName:
        Description: Environment prefixed to each resource
        Type: String
    BucketName:
        Description: Name of the bucket to be deployed
        Type: String
Resources:
    S3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref BucketName
