apiVersion: apps/v1
kind: Deployment
metadata:
    name: flask-server
spec:
    selector:
        matchLabels:
            run: flask-server
    replicas: 8
    template:
        metadata:
            labels:
                run: flask-server
        spec:
            containers:
                - name: flask-server
                  image: marcecardozo/flask-example:latest
                  ports:
                      - containerPort: 5000
                  resources:
                      limits:
                          cpu: 500m
                      requests:
                          cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
    name: flask-server
    labels:
        run: flask-server
spec:
    ports:
        - port: 80
          targetPort: 5000
    selector:
        run: flask-server
    type: NodePort
