version: '3'
services:
    jenkins-ansible:
        container_name: jenkins-ansible
        build:
          context: .
        ports: 
            - "8080:8080"
            - "50000:50000"
        volumes: 
            - ./jenkins_home:/var/jenkins_home
        networks: 
            - net
networks:
    net: